(function(){
var R=[
{id:'rookie',name:'Новичковый заезд',level:'Низкая',fee:0,prizeMin:30,prizeMax:60,distance:1000,opponents:3,classOffset:-12,desc:'Простой старт для молодой или слабой лошади.'},
{id:'standard',name:'Обычный заезд',level:'Средняя',fee:25,prizeMin:80,prizeMax:150,distance:1600,opponents:5,classOffset:0,desc:'Базовый формат: нормальные соперники и честный приз.'},
{id:'strong',name:'Сильный заезд',level:'Высокая',fee:50,prizeMin:180,prizeMax:300,distance:2000,opponents:6,classOffset:10,desc:'Серьёзная проверка для прокачанных лошадей.'},
{id:'elite',name:'Элитный заезд',level:'Очень высокая',fee:100,prizeMin:400,prizeMax:700,distance:2400,opponents:7,classOffset:20,desc:'Большой риск и большой приз. Нужна сильная конюшня.'}
];
var bots=['Гром','Тайфун','Северный Ветер','Золотой Барс','Красный Шторм','Феникс','Ледяной','Циклон','Буревестник','Рассвет'];
var H={
'Скорость':'Максимальный темп лошади на дистанции. Чем выше скорость, тем быстрее лошадь идёт на прямых участках.',
'Выносливость':'Помогает не проседать ближе к финишу. Особенно важна на длинных заездах.',
'Ускорение':'Влияет на старт и короткие рывки во время гонки.',
'Манёвренность':'Помогает менять дорожку, обходить соперников и терять меньше скорости при перестроении.',
'Сила':'Запас мощности. Помогает держать темп и стабильнее проходить плотную борьбу.',
'Интеллект':'Влияет на выбор траектории и шанс избежать ошибки или сбоя.',
'Энергия':'Текущее состояние лошади. Низкая энергия ухудшает результат в гонке.',
'Потенциал':'Запас развития. Чем выше потенциал, тем перспективнее тренировки.',
'Характер':'Особый стиль поведения в гонке: рывки, риск, стабильность или частая смена дорожек.',
'Класс':'Средняя сила лошади по всем основным параметрам.'
};
var raceId='standard',myHorseId=null,activeRace=null,boardTimer=null;
var oldShowScreen=typeof showScreen==='function'?showScreen:null;
var oldShowResults=typeof showResults==='function'?showResults:null;
var oldRenderStable=typeof renderStable==='function'?renderStable:null;
var oldRenderTraining=typeof renderTrainingScreen==='function'?renderTrainingScreen:null;
var oldCreateRace=typeof createRaceGame==='function'?createRaceGame:null;
function id(x){return document.getElementById(x)}
function money(){return typeof coins==='number'?coins:0}
function race(){return R.find(function(x){return x.id===raceId})||R[1]}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function addScreens(){
var main=document.createElement('div');main.id='mainMenuScreen';main.className='screen';main.innerHTML='<div class="topbar"><div class="topbar-row"><div style="width:38px;flex:0 0 auto"></div><div class="topbar-title"><h1>ГЛАВНОЕ МЕНЮ</h1><p>Конюшня, гонки и развитие</p></div><button class="icon-btn" id="mainInfoBtn">i</button></div></div><div class="content-scroll" id="mainMenuScroll"></div>';
var rm=document.createElement('div');rm.id='raceMenuScreen';rm.className='screen';rm.innerHTML='<div class="topbar"><div class="topbar-row"><button class="icon-btn" id="raceMenuBackBtn">←</button><div class="topbar-title"><h1>ГОНКИ</h1><p>Выберите заезд и свою лошадь</p></div><div style="width:38px;flex:0 0 auto"></div></div></div><div class="content-scroll" id="raceMenuScroll"></div><div class="race-start-panel"><button class="btn btn-gold" id="raceMenuStartBtn" style="width:100%">Начать заезд</button></div>';
var hp=document.createElement('div');hp.id='helpPop';hp.className='help-pop';hp.innerHTML='<div class="help-title"></div><div class="help-text"></div>';
document.body.insertBefore(main,document.body.firstChild);document.body.insertBefore(rm,document.body.firstChild);document.body.appendChild(hp)}
function fixStableTopbar(){var b=id('resetBtn');if(b&&!id('stableBackMenuBtn')){b.id='stableBackMenuBtn';b.textContent='←';b.title='В главное меню'}var p=document.querySelector('#stableScreen .topbar-title p');if(p)p.textContent='Ваши лошади и развитие конюшни'}
function hideAll(){Array.prototype.forEach.call(document.querySelectorAll('.screen'),function(s){s.classList.remove('active')})}
showScreen=function(name){
if(name==='menu'){hideAll();id('mainMenuScreen').classList.add('active');renderMain();return}
if(name==='raceMenu'){hideAll();id('raceMenuScreen').classList.add('active');renderRaceMenu();return}
if(oldShowScreen)oldShowScreen(name);var m=id('mainMenuScreen'),r=id('raceMenuScreen');if(m)m.classList.remove('active');if(r)r.classList.remove('active');if(name==='race')document.body.classList.add('race-readable');else document.body.classList.remove('race-readable')};
function tile(a,ic,t,d,dis){return '<button class="menu-tile '+(dis?'disabled':'')+'" data-menu="'+a+'"><div class="menu-icon">'+ic+'</div><div><div class="menu-title">'+t+'</div><div class="menu-desc">'+d+'</div></div></button>'}
function renderMain(){var el=id('mainMenuScroll');var n=Array.isArray(horses)?horses.length:0;var avg=typeof averageClass==='function'?averageClass():0;el.innerHTML='<section class="main-menu-hero"><div class="main-menu-title">СКАЧКИ</div><div class="main-menu-sub">Развивайте конюшню, выбирайте лошадь и участвуйте в заездах с разным взносом и силой соперников.</div><div class="main-menu-stats"><div class="chip-box"><div class="value">🪙 '+money()+'</div><div class="label">Баланс</div></div><div class="chip-box"><div class="value">'+n+'</div><div class="label">Лошадей</div></div><div class="chip-box"><div class="value helpable" data-help="Класс">'+avg+'</div><div class="label">Класс</div></div></div></section>'+tile('stable','🐴','Конюшня','Ваши лошади, тренировки и характеристики')+tile('races','🏁','Гонки','Заезды, взносы, соперники и призы')+tile('breed','🧬','Разведение','Новые потомки')+tile('rating','🏆','Рейтинг','Скоро',true);markHelp(el)}
function raceCard(x){var s=x.id===raceId;return '<div class="race-card '+(s?'selected':'')+'" data-race="'+x.id+'"><div class="race-top"><div><div class="race-title">'+x.name+'</div><div class="race-desc">'+x.desc+'</div></div><div class="race-fee">'+x.fee+' 🪙</div></div><div class="race-grid"><div class="race-box"><b>'+x.level+'</b><span>Соперники</span></div><div class="race-box"><b>'+x.distance+' м</b><span>Дистанция</span></div><div class="race-box"><b>'+x.prizeMin+'–'+x.prizeMax+'</b><span>Приз</span></div></div></div>'}
function note(h,rc,cl){var target=65+rc.classOffset,d=cl-target,e=h.energy<25?' Энергии мало.':h.energy<55?' Энергия средняя.':' Энергия хорошая.';if(d>=12)return 'Сильный выбор для этого заезда.'+e;if(d>=-3)return 'Подходит для этого уровня.'+e;return 'Будет тяжело: соперники сильнее.'+e}
function horseCard(h){var rc=race(),cl=typeof horseClass==='function'?horseClass(h):0,s=String(h.id)===String(myHorseId);return '<div class="my-horse-card '+(s?'selected':'')+'" data-horse="'+h.id+'"><div class="horse-avatar"><img src="./horse_icon.png" alt="horse"></div><div class="my-horse-info"><div class="my-horse-name">'+h.name+' '+(s?'<span class="player-badge">Выбрана</span>':'')+'</div><div class="select-badges"><span class="mini-tag helpable" data-help="Класс">Класс '+cl+'</span><span class="mini-tag helpable" data-help="Энергия">Энергия '+h.energy+'</span><span class="mini-tag helpable" data-help="Характер">'+h.temperament+'</span></div><div class="my-horse-note">'+note(h,rc,cl)+'</div></div></div>'}
function renderRaceMenu(){var el=id('raceMenuScroll');if(!myHorseId&&horses&&horses[0])myHorseId=String(horses[0].id);el.innerHTML='<section class="selection-summary"><div><div class="summary-title">Доступные заезды</div><div class="summary-desc">Выберите уровень гонки и одну свою лошадь. Соперники создаются автоматически.</div></div><div class="selection-count"><span>🪙</span><small>'+money()+'</small></div></section><div class="section-label">Тип гонки</div>'+R.map(raceCard).join('')+'<div class="section-label">Ваша лошадь</div>'+(horses||[]).map(horseCard).join('');var rc=race();id('raceMenuStartBtn').textContent='Начать заезд • взнос '+rc.fee+' 🪙';markHelp(el)}
function bot(base,i){function s(){return clamp(base+randInt(-8,8),35,100)}return {id:'bot_'+Date.now()+'_'+i,name:bots[i%bots.length],speed:s(),stamina:s(),acceleration:s(),agility:s(),power:s(),intelligence:s(),potential:clamp(base+randInt(-5,10),50,100),energy:randInt(75,100),temperament:temperaments[randInt(0,temperaments.length-1)],isBot:true}}
function start(){var rc=race();var h=(horses||[]).find(function(x){return String(x.id)===String(myHorseId)});if(!h)return showToast('Выберите свою лошадь');if(money()<rc.fee)return showToast('Недостаточно монет для взноса');coins-=rc.fee;if(typeof saveGame==='function')saveGame();activeRace=rc;var base=clamp((typeof horseClass==='function'?horseClass(h):65)+rc.classOffset,35,100);var me=JSON.parse(JSON.stringify(h));me.name='Вы: '+me.name;me.isPlayer=true;me.playerHorseId=h.id;currentRaceHorses=[me];for(var i=0;i<rc.opponents;i++)currentRaceHorses.push(bot(base,i));raceResults=[];showScreen('race');raceStatusEl.textContent=rc.name+': взнос '+rc.fee+' 🪙, приз '+rc.prizeMin+'–'+rc.prizeMax+' 🪙.';setTimeout(createRaceGame,40)}
function markHelp(root){Array.prototype.forEach.call((root||document).querySelectorAll('.stat-top span,.mini-tag,.chip-box .label'),function(el){var t=(el.textContent||'').trim();Object.keys(H).forEach(function(k){if(t.indexOf(k)===0){el.classList.add('helpable');el.setAttribute('data-help',k)}})})}
function popHelp(k){var p=id('helpPop');if(!p||!H[k])return;p.querySelector('.help-title').textContent=k;p.querySelector('.help-text').textContent=H[k];p.classList.add('active');clearTimeout(popHelp.t);popHelp.t=setTimeout(function(){p.classList.remove('active')},4200)}
renderStable=function(){if(oldRenderStable)oldRenderStable();fixStableTopbar();markHelp(id('stableScreen'))};
renderTrainingScreen=function(h){if(oldRenderTraining)oldRenderTraining(h);markHelp(id('trainingScreen'))};
createRaceGame=function(){if(oldCreateRace)oldCreateRace();setTimeout(setupRaceOverlay,120)};
function setupRaceOverlay(){var box=id('phaserBox');if(!box)return;box.style.position='relative';var old=id('raceDomBoard');if(old)old.remove();var o=document.createElement('div');o.id='raceDomBoard';o.style.cssText='position:absolute;left:10px;right:10px;top:10px;z-index:50;pointer-events:none;display:flex;gap:8px;align-items:flex-start;justify-content:space-between';o.innerHTML='<div id="racePlayerBox" style="background:rgba(8,20,35,.88);border:1px solid rgba(255,255,255,.18);border-radius:14px;padding:8px 10px;color:#fff;font-weight:900;font-size:13px;max-width:45%">ВЫ</div><div id="raceBigBoard" style="background:rgba(8,20,35,.88);border:1px solid rgba(255,255,255,.18);border-radius:14px;padding:8px 10px;color:#fff;font-weight:900;font-size:13px;min-width:145px;text-align:left"></div>';box.appendChild(o);clearInterval(boardTimer);boardTimer=setInterval(updateRaceOverlay,220);updateRaceOverlay()}
function updateRaceOverlay(){var scene=raceGame&&raceGame.scene&&raceGame.scene.scenes&&raceGame.scene.scenes[0];var b=id('raceBigBoard'),p=id('racePlayerBox');if(!scene||!scene.runners||!b)return;var arr=scene.runners.slice().sort(function(a,b){return b.progress-a.progress});b.innerHTML=arr.slice(0,5).map(function(r,i){var me=r.horse&&r.horse.isPlayer;var nm=(r.horse.name||'').replace('Вы: ','');var pc=Math.min(100,Math.round((r.progress/(scene.totalLaps||1))*100));return '<div style="color:'+(me?'#ffd34d':'#dce8f2')+';margin:2px 0">'+(i+1)+'. '+(me?'ВЫ: ':'')+nm+' • '+pc+'%</div>'}).join('');var me=arr.find(function(r){return r.horse&&r.horse.isPlayer});if(p&&me){var place=arr.indexOf(me)+1;var pc2=Math.min(100,Math.round((me.progress/(scene.totalLaps||1))*100));p.innerHTML='Ваша лошадь<br><span style="color:#ffd34d;font-size:17px">'+place+' место • '+pc2+'%</span>'}}
showResults=function(){clearInterval(boardTimer);boardTimer=null;if(!activeRace)return oldShowResults?oldShowResults():null;raceResults.sort(function(a,b){return parseFloat(a.time)-parseFloat(b.time)});var pi=raceResults.findIndex(function(x){return x.horse&&x.horse.isPlayer});var place=pi+1,rc=activeRace,pay=0;if(place===1)pay=rc.prizeMax;else if(place===2)pay=Math.round((rc.prizeMin+rc.prizeMax)/2);else if(place===3)pay=rc.prizeMin;coins+=pay;var pr=raceResults[pi];if(pr&&pr.horse&&pr.horse.playerHorseId){var real=horses.find(function(x){return String(x.id)===String(pr.horse.playerHorseId)});if(real)real.energy=Math.max(0,real.energy-randInt(6,12))}if(typeof saveGame==='function')saveGame();if(typeof renderStable==='function')renderStable();var total=pay>0?'+'+pay+' 🪙':'-'+rc.fee+' 🪙';resultsListEl.innerHTML='<div class="results-header"><div class="winner-banner"><div class="winner-crown">🏁</div><div class="winner-main"><div class="winner-place">Ваш результат</div><div class="winner-name">'+(place||'—')+' место</div><div class="winner-time">'+rc.name+' • итог: '+total+'</div></div></div></div>'+raceResults.map(function(it,idx){var me=it.horse&&it.horse.isPlayer;return '<div class="result-item"><div class="result-head"><div><div style="font-size:16px;font-weight:900">'+(idx+1)+'. '+it.name+(me?' <span class="player-badge">Вы</span>':'')+'</div><div style="font-size:12px;color:var(--muted);margin-top:4px">Время: '+it.time+' сек</div></div><div class="result-reward">'+(me?total:'')+'</div></div></div>'}).join('')+'<button class="btn btn-gold" id="resultRaceMenuBtn" style="width:100%;margin-top:12px">В меню гонок</button><button class="btn btn-dark" id="resultMainMenuBtn" style="width:100%;margin-top:10px">В главное меню</button>';resultsModal.classList.add('active');setTimeout(function(){var a=id('resultRaceMenuBtn'),m=id('resultMainMenuBtn');if(a)a.onclick=function(){resultsModal.classList.remove('active');showScreen('raceMenu')};if(m)m.onclick=function(){resultsModal.classList.remove('active');showScreen('menu')}},0);showToast(pay>0?'Выигрыш: 🪙 '+pay:'Приз не получен');activeRace=null};
function bind(){id('mainMenuScroll').addEventListener('click',function(e){var a=e.target.closest('[data-menu]');if(!a)return;var v=a.getAttribute('data-menu');if(v==='stable')return showScreen('stable');if(v==='races')return showScreen('raceMenu');if(v==='breed')return openBreedModal();if(v==='rating')return showToast('Рейтинг добавим позже')});id('raceMenuBackBtn').addEventListener('click',function(){showScreen('menu')});id('raceMenuScroll').addEventListener('click',function(e){var rc=e.target.closest('[data-race]');if(rc){raceId=rc.getAttribute('data-race');renderRaceMenu();return}var hc=e.target.closest('[data-horse]');if(hc){myHorseId=hc.getAttribute('data-horse');renderRaceMenu()}});id('raceMenuStartBtn').addEventListener('click',start);id('mainInfoBtn').addEventListener('click',function(){if(infoModal)infoModal.classList.add('active')});document.addEventListener('click',function(e){var h=e.target.closest('.helpable');if(h){e.preventDefault();e.stopPropagation();popHelp(h.getAttribute('data-help')||h.textContent.trim())}else if(!e.target.closest('.help-pop')){var p=id('helpPop');if(p)p.classList.remove('active')}},true);var rb=id('raceBackBtn');if(rb)rb.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();clearInterval(boardTimer);destroyRaceGame();showScreen('raceMenu')},true);var orb=id('openRaceBtn');if(orb){orb.textContent='Гонки';orb.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();showScreen('raceMenu')},true)}document.addEventListener('click',function(e){if(e.target&&e.target.id==='stableBackMenuBtn'){e.preventDefault();e.stopImmediatePropagation();showScreen('menu')}},true);var bb=id('breedBackBtn');if(bb)bb.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();showScreen('menu')},true)}
addScreens();fixStableTopbar();bind();if(oldRenderStable)renderStable();renderMain();showScreen('menu');
})();
