(function(){
var R=[
{id:'rookie',name:'Новичковый заезд',level:'Низкая',fee:10,prizeMin:30,prizeMax:60,distance:1000,opponents:3,classOffset:-12,desc:'Простой старт для молодой или слабой лошади.'},
{id:'standard',name:'Обычный заезд',level:'Средняя',fee:25,prizeMin:80,prizeMax:150,distance:1600,opponents:5,classOffset:0,desc:'Базовый формат: нормальные соперники и честный приз.'},
{id:'strong',name:'Сильный заезд',level:'Высокая',fee:50,prizeMin:180,prizeMax:300,distance:2000,opponents:6,classOffset:10,desc:'Серьёзная проверка для прокачанных лошадей.'},
{id:'elite',name:'Элитный заезд',level:'Очень высокая',fee:100,prizeMin:400,prizeMax:700,distance:2400,opponents:7,classOffset:20,desc:'Большой риск и большой приз. Нужна сильная конюшня.'}
];
var bots=['Гром','Тайфун','Северный Ветер','Золотой Барс','Красный Шторм','Феникс','Ледяной','Циклон','Буревестник','Рассвет'];
var raceId='standard';
var myHorseId=null;
var activeRace=null;
var oldShowScreen=typeof showScreen==='function'?showScreen:null;
var oldShowResults=typeof showResults==='function'?showResults:null;
function id(x){return document.getElementById(x)}
function money(){return typeof coins==='number'?coins:0}
function race(){return R.find(function(x){return x.id===raceId})||R[1]}
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function addScreens(){
var main=document.createElement('div');main.id='mainMenuScreen';main.className='screen';main.innerHTML='<div class="topbar"><div class="topbar-row"><div style="width:38px;flex:0 0 auto"></div><div class="topbar-title"><h1>ГЛАВНОЕ МЕНЮ</h1><p>Конюшня, гонки и развитие</p></div><button class="icon-btn" id="mainInfoBtn">i</button></div></div><div class="content-scroll" id="mainMenuScroll"></div>';
var rm=document.createElement('div');rm.id='raceMenuScreen';rm.className='screen';rm.innerHTML='<div class="topbar"><div class="topbar-row"><button class="icon-btn" id="raceMenuBackBtn">←</button><div class="topbar-title"><h1>ГОНКИ</h1><p>Выберите заезд и свою лошадь</p></div><div style="width:38px;flex:0 0 auto"></div></div></div><div class="content-scroll" id="raceMenuScroll"></div><div class="race-start-panel"><button class="btn btn-gold" id="raceMenuStartBtn" style="width:100%">Начать заезд</button></div>';
document.body.insertBefore(main,document.body.firstChild);document.body.insertBefore(rm,document.body.firstChild)}
function hideAll(){Array.prototype.forEach.call(document.querySelectorAll('.screen'),function(s){s.classList.remove('active')})}
showScreen=function(name){
if(name==='menu'){hideAll();id('mainMenuScreen').classList.add('active');renderMain();return}
if(name==='raceMenu'){hideAll();id('raceMenuScreen').classList.add('active');renderRaceMenu();return}
if(oldShowScreen)oldShowScreen(name);var m=id('mainMenuScreen'),r=id('raceMenuScreen');if(m)m.classList.remove('active');if(r)r.classList.remove('active')};
function tile(a,ic,t,d,dis){return '<button class="menu-tile '+(dis?'disabled':'')+'" data-menu="'+a+'"><div class="menu-icon">'+ic+'</div><div><div class="menu-title">'+t+'</div><div class="menu-desc">'+d+'</div></div></button>'}
function renderMain(){var el=id('mainMenuScroll');var n=Array.isArray(horses)?horses.length:0;var avg=typeof averageClass==='function'?averageClass():0;el.innerHTML='<section class="main-menu-hero"><div class="main-menu-title">СКАЧКИ</div><div class="main-menu-sub">Развивайте конюшню, выбирайте лошадь и участвуйте в заездах с разным взносом и силой соперников.</div><div class="main-menu-stats"><div class="chip-box"><div class="value">🪙 '+money()+'</div><div class="label">Баланс</div></div><div class="chip-box"><div class="value">'+n+'</div><div class="label">Лошадей</div></div><div class="chip-box"><div class="value">'+avg+'</div><div class="label">Класс</div></div></div></section>'+tile('stable','🐴','Конюшня','Ваши лошади, тренировки и характеристики')+tile('races','🏁','Гонки','Заезды, взносы, соперники и призы')+tile('breed','🧬','Разведение','Новые потомки')+tile('rating','🏆','Рейтинг','Скоро',true)}
function raceCard(x){var s=x.id===raceId;return '<div class="race-card '+(s?'selected':'')+'" data-race="'+x.id+'"><div class="race-top"><div><div class="race-title">'+x.name+'</div><div class="race-desc">'+x.desc+'</div></div><div class="race-fee">'+x.fee+' 🪙</div></div><div class="race-grid"><div class="race-box"><b>'+x.level+'</b><span>Соперники</span></div><div class="race-box"><b>'+x.distance+' м</b><span>Дистанция</span></div><div class="race-box"><b>'+x.prizeMin+'–'+x.prizeMax+'</b><span>Приз</span></div></div></div>'}
function note(h,rc,cl){var target=65+rc.classOffset,d=cl-target,e=h.energy<25?' Энергии мало.':h.energy<55?' Энергия средняя.':' Энергия хорошая.';if(d>=12)return 'Сильный выбор для этого заезда.'+e;if(d>=-3)return 'Подходит для этого уровня.'+e;return 'Будет тяжело: соперники сильнее.'+e}
function horseCard(h){var rc=race(),cl=typeof horseClass==='function'?horseClass(h):0,s=String(h.id)===String(myHorseId);return '<div class="my-horse-card '+(s?'selected':'')+'" data-horse="'+h.id+'"><div class="horse-avatar"><img src="./horse_icon.png" alt="horse"></div><div class="my-horse-info"><div class="my-horse-name">'+h.name+' '+(s?'<span class="player-badge">Выбрана</span>':'')+'</div><div class="select-badges"><span class="mini-tag">Класс '+cl+'</span><span class="mini-tag">Энергия '+h.energy+'</span><span class="mini-tag">'+h.temperament+'</span></div><div class="my-horse-note">'+note(h,rc,cl)+'</div></div></div>'}
function renderRaceMenu(){var el=id('raceMenuScroll');if(!myHorseId&&horses&&horses[0])myHorseId=String(horses[0].id);el.innerHTML='<section class="selection-summary"><div><div class="summary-title">Доступные заезды</div><div class="summary-desc">Выберите уровень гонки и одну свою лошадь. Соперники создаются автоматически.</div></div><div class="selection-count"><span>🪙</span><small>'+money()+'</small></div></section><div class="section-label">Тип гонки</div>'+R.map(raceCard).join('')+'<div class="section-label">Ваша лошадь</div>'+(horses||[]).map(horseCard).join('');var rc=race();id('raceMenuStartBtn').textContent='Начать заезд • взнос '+rc.fee+' 🪙'}
function bot(base,i){function s(){return clamp(base+randInt(-8,8),35,100)}return {id:'bot_'+Date.now()+'_'+i,name:bots[i%bots.length],speed:s(),stamina:s(),acceleration:s(),agility:s(),power:s(),intelligence:s(),potential:clamp(base+randInt(-5,10),50,100),energy:randInt(75,100),temperament:temperaments[randInt(0,temperaments.length-1)],isBot:true}}
function start(){var rc=race();var h=(horses||[]).find(function(x){return String(x.id)===String(myHorseId)});if(!h)return showToast('Выберите свою лошадь');if(money()<rc.fee)return showToast('Недостаточно монет для взноса');coins-=rc.fee;if(typeof saveGame==='function')saveGame();activeRace=rc;var base=clamp((typeof horseClass==='function'?horseClass(h):65)+rc.classOffset,35,100);var me=JSON.parse(JSON.stringify(h));me.name='Вы: '+me.name;me.isPlayer=true;me.playerHorseId=h.id;currentRaceHorses=[me];for(var i=0;i<rc.opponents;i++)currentRaceHorses.push(bot(base,i));raceResults=[];showScreen('race');raceStatusEl.textContent=rc.name+': взнос '+rc.fee+' 🪙, приз '+rc.prizeMin+'–'+rc.prizeMax+' 🪙.';setTimeout(createRaceGame,40)}
showResults=function(){if(!activeRace)return oldShowResults?oldShowResults():null;raceResults.sort(function(a,b){return parseFloat(a.time)-parseFloat(b.time)});var pi=raceResults.findIndex(function(x){return x.horse&&x.horse.isPlayer});var place=pi+1,rc=activeRace,pay=0;if(place===1)pay=rc.prizeMax;else if(place===2)pay=Math.round((rc.prizeMin+rc.prizeMax)/2);else if(place===3)pay=rc.prizeMin;coins+=pay;var pr=raceResults[pi];if(pr&&pr.horse&&pr.horse.playerHorseId){var real=horses.find(function(x){return String(x.id)===String(pr.horse.playerHorseId)});if(real)real.energy=Math.max(0,real.energy-randInt(6,12))}if(typeof saveGame==='function')saveGame();if(typeof renderStable==='function')renderStable();var total=pay>0?'+'+pay+' 🪙':'-'+rc.fee+' 🪙';resultsListEl.innerHTML='<div class="results-header"><div class="winner-banner"><div class="winner-crown">🏁</div><div class="winner-main"><div class="winner-place">Ваш результат</div><div class="winner-name">'+(place||'—')+' место</div><div class="winner-time">'+rc.name+' • итог: '+total+'</div></div></div></div>'+raceResults.map(function(it,idx){var me=it.horse&&it.horse.isPlayer;return '<div class="result-item"><div class="result-head"><div><div style="font-size:16px;font-weight:900">'+(idx+1)+'. '+it.name+(me?' <span class="player-badge">Вы</span>':'')+'</div><div style="font-size:12px;color:var(--muted);margin-top:4px">Время: '+it.time+' сек</div></div><div class="result-reward">'+(me?total:'')+'</div></div></div>'}).join('');resultsModal.classList.add('active');showToast(pay>0?'Выигрыш: 🪙 '+pay:'Приз не получен');activeRace=null};
function bind(){id('mainMenuScroll').addEventListener('click',function(e){var a=e.target.closest('[data-menu]');if(!a)return;var v=a.getAttribute('data-menu');if(v==='stable')return showScreen('stable');if(v==='races')return showScreen('raceMenu');if(v==='breed')return openBreedModal();if(v==='rating')return showToast('Рейтинг добавим позже')});id('raceMenuBackBtn').addEventListener('click',function(){showScreen('menu')});id('raceMenuScroll').addEventListener('click',function(e){var rc=e.target.closest('[data-race]');if(rc){raceId=rc.getAttribute('data-race');renderRaceMenu();return}var hc=e.target.closest('[data-horse]');if(hc){myHorseId=hc.getAttribute('data-horse');renderRaceMenu()}});id('raceMenuStartBtn').addEventListener('click',start);id('mainInfoBtn').addEventListener('click',function(){if(infoModal)infoModal.classList.add('active')});var rb=id('raceBackBtn');if(rb)rb.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();destroyRaceGame();showScreen('raceMenu')},true);var orb=id('openRaceBtn');if(orb){orb.textContent='Гонки';orb.addEventListener('click',function(e){e.preventDefault();e.stopImmediatePropagation();showScreen('raceMenu')},true)}}
addScreens();bind();renderMain();showScreen('menu');
})();
